#!/bin/env bash
#
#	script to refresh the tools used to support programming wiht the Go language
#	donwloads and build the apps placing them in $GPATH/bin directory
#
#	craeteed by Simon Rowe <simon@wiremoons.com> on 11 Sep 2016
#
printf "\nRebuilding Go language support apps...\n"
sleep 2
if [ -x $GOROOT/bin/go ] ; then
	go get -u -v github.com/nsf/gocode
	go get -u -v github.com/rogpeppe/godef
	go get -u -v github.com/golang/lint/golint
	go get -u -v github.com/lukehoban/go-outline
	go get -u -v sourcegraph.com/sqs/goreturns
	go get -u -v golang.org/x/tools/cmd/gorename
	go get -u -v github.com/tpng/gopkgs
	go get -u -v github.com/newhook/go-symbols
	go get -u -v golang.org/x/tools/cmd/guru
else
	printf"Unable to locate you 'go' binary to run command - check '$GOROO/bin/go'"
fi

printf "\nDONE\n"
