#!/usr/bin/env bash
#
#  Script to run Sublime Text from the command line
#
if [ -x /opt/sublime_text/sublime_text ] ; then
	# run sublime_text passing all command line parameters and redirect any output to /dev/null
	# as sublime often prints out lots of Gdk warnings. Also background process to free the
	# console / terminal for further use
	/opt/sublime_text/sublime_text ${*} > /dev/null 2>&1 &
else
	echo "ERROR: unbale to locate or run: /opt/sublime_text/sublime_text"
fi

